# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pdist_intrinsic <- function(X, mfdname) {
    .Call('_RiemBaseExt_pdist_intrinsic', PACKAGE = 'RiemBaseExt', X, mfdname)
}

pdist_extrinsic <- function(X, mfdname) {
    .Call('_RiemBaseExt_pdist_extrinsic', PACKAGE = 'RiemBaseExt', X, mfdname)
}

convert_3toM <- function(X, mfdname) {
    .Call('_RiemBaseExt_convert_3toM', PACKAGE = 'RiemBaseExt', X, mfdname)
}

cpp_equivariant <- function(X, mfdname) {
    .Call('_RiemBaseExt_cpp_equivariant', PACKAGE = 'RiemBaseExt', X, mfdname)
}

cpp_distint <- function(X, mfdname) {
    .Call('_RiemBaseExt_cpp_distint', PACKAGE = 'RiemBaseExt', X, mfdname)
}

cpp_dist2int <- function(X, Y, mfdname) {
    .Call('_RiemBaseExt_cpp_dist2int', PACKAGE = 'RiemBaseExt', X, Y, mfdname)
}

cpp_distext <- function(X, mfdname) {
    .Call('_RiemBaseExt_cpp_distext', PACKAGE = 'RiemBaseExt', X, mfdname)
}

cpp_dist2ext <- function(X, Y, mfdname) {
    .Call('_RiemBaseExt_cpp_dist2ext', PACKAGE = 'RiemBaseExt', X, Y, mfdname)
}

cpp_dispersion <- function(X, xmean, mfdname) {
    .Call('_RiemBaseExt_cpp_dispersion', PACKAGE = 'RiemBaseExt', X, xmean, mfdname)
}

frechet_extrinsic <- function(X, mfdname) {
    .Call('_RiemBaseExt_frechet_extrinsic', PACKAGE = 'RiemBaseExt', X, mfdname)
}

frechet_intrinsic <- function(x, X, mfdname) {
    .Call('_RiemBaseExt_frechet_intrinsic', PACKAGE = 'RiemBaseExt', x, X, mfdname)
}

